### ISSUE TITLE
Does not able to subscribe Private channels

### ISSUE THREAD

**Issue by Zain-Waheed** [kerimamansaryyev/dart_pusher_channels#31] opened 2023-07-04 19:17 UTC
I am connected to a private channel, but I am unable to subscribe to it due to a 403 Forbidden error and failed authorization. And also I do not find a way to give the signature. 
Here is the exception through it 
Exception:Failed to get authorization data. Response to https://api.dateifyapp.com/broadcasting/auth was:
I/flutter (18183):  {
I/flutter (18183):     "message": "",
I/flutter (18183):     "exception": "Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException",
I/flutter (18183):     "file": "/var/app/current/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php",
I/flutter (18183):     "line": 82,
I/flutter (18183):     "trace": [
I/flutter (18183):         {
I/flutter (18183):             "file": "/var/app/current/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastManager.php",
I/flutter (18183):             "line": 479,
I/flutter (18183):             "function": "auth",
I/flutter (18183):             "class": "Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster",
I/flutter (18183):             "type": "->"
I/flutter (18183):         },
I/flutter (18183):         {
I/flutter (18183):             "file": "/var/app/current/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php",
I/flutter (18183):             "line": 353,
I/flutter (18183):             "function": "__call",
I/flutter (18183):             "class": "Illuminate\\Broadcasting\\BroadcastManager",
I/flutter (18183):             "type": "->"
I/flutter (18183):         },
I/flutter (18183):         {
I/flutter (18183):             "file": "/var/app/current/vendor/

**Comment by kerimamansaryyev** [comment] 2023-07-04 19:19
@Zain-Waheed What kind of signature?

**Comment by kerimamansaryyev** [comment] 2023-07-04 19:20
@Zain-Waheed It would be easier if you provide me a portion of sample code to reproduce the issue

**Comment by mimoislam** [comment] 2023-07-04 22:02
Same here 
I/flutter (27787): Received an event: {"event":"pusher_internal:subscription_succeeded","channel":"private-client.51"}
I/flutter (27787): Got an event, continuing activity
I/flutter (27787): Timer was canceled
I/flutter (27787): Timer is set to: 0:00:30.000000
I/flutter (27787): Attempt to trigger: {"event":"client-event","channel":"private-client.51","data":{"hello":"Hello"}}
I/flutter (27787): Received an event: {"event":"pusher:error","channel":"private-client.51","data":{"code":4301,"message":"The app does not have client messaging enabled."}}

**Comment by Zain-Waheed** [comment] 2023-07-05 05:30
getSignature(String value) {
  var key = utf8.encode('My_key');
  var bytes = utf8.encode(value);

  var hmacSha256 = Hmac(sha256, key); // HMAC-SHA256
  var digest = hmacSha256.convert(bytes);
  print("HMAC signature in string is: $digest");
  return digest;
}

dynamic onAuthorizer(String channelName, String socketId, dynamic options) {

  return {
    "auth": "My_Key:${getSignature("$socketId:$channelName")}",
  };
}

Here is the auth that is worked in the package of pusher_channels_flutter but in this case I did not find a way to give this
as mentioned  in  https://pusher.com/docs/channels/library_auth_reference/auth-signatures/

**Comment by Zain-Waheed** [comment] 2023-07-05 05:31
Here is my Code
  PrivateChannel myPrivateChannel =
  client.privateChannel(
    'private-post',
    authorizationDelegate:
    EndpointAuthorizableChannelTokenAuthorizationDelegate.forPrivateChannel(
      authorizationEndpoint:
      Uri.parse('https://api.dateifyapp.com/broadcasting/auth'),
      headers: const {
        'Accept': 'application/json',
        'Authorization': 'Bearer 52|ENWIR6ACXfIO4YWI6HBpUVze6bZVNzhsu5Z545qn',
      },
      // parser:_parser,
      onAuthFailed: myOnAuthFailedFunction,
    ),
  );

**Comment by kerimamansaryyev** [comment] 2023-07-08 16:43
@Zain-Waheed Your code is unformatted, put yourself in my shoes, how shell I understand the code?

**Comment by kerimamansaryyev** [comment] 2023-07-08 16:55
@Zain-Waheed For me to help the issue it is important that you:
1. Describe what are you trying to accomplish.
2. Tell me what didn't work.
3. Provide detailed steps of your actions
4. Describe in which step it didn't  work.

And format your code with mark-down otherwise I am unable to understand it.

And which is the  most important:
Before considering to open the issue for client library, check up your server configurations, check if your authorization endpoint works correctly. I'll be waiting for a while to help you with the issue, if I don't hear from you - I will close the issue.

**Comment by kerimamansaryyev** [comment] 2023-07-21 07:09
Closing due to inactivity

**Closed by kerimamansaryyev** 2023-07-21 07:09 UTC
