### ISSUE TITLE
Trigger not working when you subscribe to new channel

### ISSUE THREAD

**Issue by zamirszn** [kerimamansaryyev/dart_pusher_channels#28] opened 2023-05-16 07:15 UTC
Issue Description:

I am currently working on implementing a one-to-one chat feature using Pusher, and I have encountered an issue with unsubscribing and subscribing to different user channels.

Steps to Reproduce:

Step1: Subscribe to a user channel using the channel name  `private-user.$chatUserId` then call  `initializePusher();`

Step 2: Trigger events on the subscribed user channel  and verify that the events are received successfully.  `unawaited(client.connect());` everything works fine here

Step3: Unsubscribe from the current user channel.  `void disposePusherChannel()`

Step 4: Subscribe to a new user channel using a different channel name.  `private-user.$chatUserId` then call  `initializePusher();`

Step 5: Trigger events on the newly subscribed user channel and observe that the events are not being received.  

Step 6: Re-subscribe to the previous user channel and verify that the events are received correctly again.  `private-user.$chatUserId` then call  `initializePusher();`

Expected Behavior:

I expect to be able to unsubscribe from a user channel and successfully subscribe to a new user channel, receiving events on the new channel.

Actual Behavior:

After unsubscribing from a user channel and subscribing to a new user channel, the events are not received on the new channel. However, when reverting back to the previous user channel, the events are received correctly.

Can you help me with this , is there something I'm missing or doing wrong?

version: dart_pusher_channels: ^1.1.0

```dart
import 'dart:async';
import 'dart:convert';

import 'package:dart_pusher_channels/dart_pusher_channels.dart';
import 'package:flutter/material.dart';
import 'package:trivhunt/shared/global/global.dart';
import 'package:trivhunt/shared/logger_service.dart';

class CommunityChatScreen extends StatefulWidget {
  const CommunityChatScreen(
      {super.key,
      required this.chatRoomId,
      required this.chatUserId,
      this.chatUserAvatar,
      this.chatUserSkill,
      this.userFullName});
  final String chatRoomId;
  final String chatUserId;
  final String? chatUserAvatar;
  final String? chatUserSkill;
  final String? userFullName;

  @override
  State<CommunityChatScreen> createState() => _CommunityChatScreenState();
}

class _CommunityChatScreenState extends State<CommunityChatScreen> {
  static late String chatUserId;
  static late String roomId;

  static String privateChannelName = "private-user.$chatUserId";
  static String receiveMessageEvent = "ReceiveChatMessage";
  static String presenceChannelName = "presence-chat.$roomId";
  static String sendChatEvent = "SendChatMessage";

  PrivateChannel? privateChannel;

  PresenceChannel? presenceChannel;

  initializePusher() {
    PusherChannelsPackageLogger.enableLogs();
    const testOptions = PusherChannelsOptions.fromCluster(
      scheme: 'wss',
      cluster: 'eu',
      key: 'used my key here',
      port: 443,
    );
    // Create an instance of PusherChannelsClient
    final client = PusherChannelsClient.websocket(
      options: testOptions,
      // Connection exceptions are handled here
      connectionErrorHandler: (exception, trace, refresh) async {
        // This method allows you to reconnect if any error is occurred.
        refresh();
      },
    );

    PresenceChannel myPresenceChannel = client.presenceChannel(
      presenceChannelName,
      authorizationDelegate:
          EndpointAuthorizableChannelTokenAuthorizationDelegate
              .forPresenceChannel(
        authorizationEndpoint: Uri.parse('$baseUrl/broadcast/presence/auth'),
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          'Authorization': 'Bearer $userToken',
        },
        onAuthFailed: (exception, trace) {
          // logger.d("exception");
        },
      ),
    );

    // presenceChannel = myPresenceChannel;

    PrivateChannel myPrivateChannel = client.privateChannel(
      privateChannelName,
      authorizationDelegate:
          EndpointAuthorizableChannelTokenAuthorizationDelegate
              .forPrivateChannel(
        authorizationEndpoint: Uri.parse('$baseUrl/broadcast/auth'),
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          'Authorization': 'Bearer $userToken',
        },
      ),
    );

    privateChannel = myPrivateChannel;

    StreamSubscription<ChannelReadEvent> myPrivateChannelEventSubs =
        myPrivateChannel.bind(receiveMessageEvent).listen((event) {
      // handleNewMessage(jsonDecode(event.data));
    });

    StreamSubscription<ChannelReadEvent> myPresenceChannelEventSubs =
        myPresenceChannel.bind(sendChatEvent).listen((event) {
      Map<String, dynamic> decodedData = jsonDecode(event.data);

      if (decodedData["payload"].containsKey("message")) {
        // handleNewMessage(decodedData);
      } else {
        logger.d('Event from the presence channel $decodedData');
      }
    });

    StreamSubscription<ChannelReadEvent> presenceMembersAddedSubs =
        myPresenceChannel.whenMemberAdded().listen((event) {
      // logger.d(
      //   'Member added, now members count is ${myPresenceChannel.state?.members?.membersCount}',
      // );
    });

    // Organizing all subscriptions into 1 for readability
    final allEventSubs = <StreamSubscription?>[
      myPrivateChannelEventSubs,
      myPresenceChannelEventSubs
    ];
    // Organizing all channels for readibility
    final allChannels = <Channel>[myPrivateChannel, myPresenceChannel];

    StreamSubscription connectionSubs =
        client.onConnectionEstablished.listen((_) {
      for (final channel in allChannels) {
        channel.subscribeIfNotUnsubscribed();
      }
    });

    // Connect with the client
    unawaited(client.connect());
  }

  void initChatHistory() {
    initializePusher();
  }

  @override
  void initState() {
    roomId = widget.chatRoomId;
    chatUserId = widget.chatUserId;
    initChatHistory();

    super.initState();
  }

  void disposePusherChannel() {
    if (presenceChannel != null) {
      presenceChannel?.unsubscribe();
    }

    if (privateChannel != null) {
      privateChannel?.unsubscribe();
    }
  }

  @override
  void dispose() {
    disposePusherChannel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return const SizedBox();
  }
}

```

**Comment by kerimamansaryyev** [comment] 2023-05-16 07:19
@zamirszn the code is unformatted and I can't read it. Please edit the issue description adding your code into the markdown code block. Like this:
```dart
var a = A();
```

**Comment by kerimamansaryyev** [comment] 2023-05-16 07:26
@zamirszn And try to add a follow-up code portion for each of the steps to reproduce the issue. So I will have better understanding.

**Comment by zamirszn** [comment] 2023-05-16 07:30
> Issue Description:
> 
> I am currently working on implementing a one-to-one chat feature using Pusher, and I have encountered an issue with unsubscribing and subscribing to different user channels.
> 
> Steps to Reproduce:
> 
> Subscribe to a user channel using the channel name `private-user.$chatUserId`
> 
> Trigger events on the subscribed user channel and verify that the events are received successfully.
> 
> Unsubscribe from the current user channel.
> 
> Subscribe to a new user channel using a different channel name.
> 
> Trigger events on the newly subscribed user channel and observe that the events are not being received.
> 
> Re-subscribe to the previous user channel and verify that the events are received correctly again.
> 
> Expected Behavior:
> 
> I expect to be able to unsubscribe from a user channel and successfully subscribe to a new user channel, receiving events on the new channel.
> 
> Actual Behavior:
> 
> After unsubscribing from a user channel and subscribing to a new user channel, the events are not received on the new channel. However, when reverting back to the previous user channel, the events are received correctly.
> 
> Can you help me with this , is there something I'm missing or doing wrong?
> 
> version: dart_pusher_channels: ^1.1.0

`import 'dart:async';
import 'dart:convert';
import 'package:dart_pusher_channels/dart_pusher_channels.dart';
import 'package:flutter/material.dart';
import 'package:trivhunt/shared/global/global.dart';
import 'package:trivhunt/shared/logger_service.dart';

class CommunityChatScreen extends StatefulWidget {
  const CommunityChatScreen(
      {super.key,
      required this.chatRoomId,
      required this.chatUserId,
      this.chatUserAvatar,
      this.chatUserSkill,
      this.userFullName});
  final String chatRoomId;
  final String chatUserId;
  final String? chatUserAvatar;
  final String? chatUserSkill;
  final String? userFullName;

  @override
  State<CommunityChatScreen> createState() => _CommunityChatScreenState();
}

class _CommunityChatScreenState extends State<CommunityChatScreen> {
  static late String chatUserId;
  static late String roomId;

  static String privateChannelName = "private-user.$chatUserId";
  static String receiveMessageEvent = "ReceiveChatMessage";
  static String presenceChannelName = "presence-chat.$roomId";
  static String sendChatEvent = "SendChatMessage";

  PrivateChannel? privateChannel;

  PresenceChannel? presenceChannel;

  initializePusher() {
    PusherChannelsPackageLogger.enableLogs();
    const testOptions = PusherChannelsOptions.fromCluster(
      scheme: 'wss',
      cluster: 'eu',
      key: 'used my key here',
      port: 443,
    );
    // Create an instance of PusherChannelsClient
    final client = PusherChannelsClient.websocket(
      options: testOptions,
      // Connection exceptions are handled here
      connectionErrorHandler: (exception, trace, refresh) async {
        // This method allows you to reconnect if any error is occurred.
        refresh();
      },
    );

    PresenceChannel myPresenceChannel = client.presenceChannel(
      presenceChannelName,
      authorizationDelegate:
          EndpointAuthorizableChannelTokenAuthorizationDelegate
              .forPresenceChannel(
        authorizationEndpoint: Uri.parse('$baseUrl/broadcast/presence/auth'),
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          'Authorization': 'Bearer $userToken',
        },
        onAuthFailed: (exception, trace) {
          // logger.d("exception");
        },
      ),
    );

    // presenceChannel = myPresenceChannel;

    PrivateChannel myPrivateChannel = client.privateChannel(
      privateChannelName,
      authorizationDelegate:
          EndpointAuthorizableChannelTokenAuthorizationDelegate
              .forPrivateChannel(
        authorizationEndpoint: Uri.parse('$baseUrl/broadcast/auth'),
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          'Authorization': 'Bearer $userToken',
        },
      ),
    );

    privateChannel = myPrivateChannel;

    StreamSubscription<ChannelReadEvent> myPrivateChannelEventSubs =
        myPrivateChannel.bind(receiveMessageEvent).listen((event) {
      // handleNewMessage(jsonDecode(event.data));
    });

    StreamSubscription<ChannelReadEvent> myPresenceChannelEventSubs =
        myPresenceChannel.bind(sendChatEvent).listen((event) {
      Map<String, dynamic> decodedData = jsonDecode(event.data);

      if (decodedData["payload"].containsKey("message")) {
        // handleNewMessage(decodedData);
      } else {
        logger.d('Event from the presence channel $decodedData');
      }
    });

    StreamSubscription<ChannelReadEvent> presenceMembersAddedSubs =
        myPresenceChannel.whenMemberAdded().listen((event) {
      // logger.d(
      //   'Member added, now members count is ${myPresenceChannel.state?.members?.membersCount}',
      // );
    });

    // Organizing all subscriptions into 1 for readability
    final allEventSubs = <StreamSubscription?>[
      myPrivateChannelEventSubs,
      myPresenceChannelEventSubs
    ];
    // Organizing all channels for readibility
    final allChannels = <Channel>[myPrivateChannel, myPresenceChannel];

    StreamSubscription connectionSubs =
        client.onConnectionEstablished.listen((_) {
      for (final channel in allChannels) {
        channel.subscribeIfNotUnsubscribed();
      }
    });

    // Connect with the client
    unawaited(client.connect());
  }

  void initChatHistory() {
    initializePusher();
  }

  @override
  void initState() {
    roomId = widget.chatRoomId;
    chatUserId = widget.chatUserId;
    initChatHistory();

    super.initState();
  }

  void disposePusherChannel() {
    if (presenceChannel != null) {
      presenceChannel?.unsubscribe();
    }

    if (privateChannel != null) {
      privateChannel?.unsubscribe();
    }
  }

  @override
  void dispose() {
    disposePusherChannel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return const SizedBox();
  }
}`

**Comment by kerimamansaryyev** [comment] 2023-05-16 07:40
@zamirszn Add corresponding logs from the package too.

**Comment by kerimamansaryyev** [comment] 2023-05-16 07:41
Can't see any changes in the description for now

**Comment by kerimamansaryyev** [comment] 2023-05-16 08:11
The code still makes no sense because it has nothing in common with the steps to reproduce because there is no code portion with actual triggering of events. But based on my understanding - you have 1 channel of received events pool and 1 channel to trigger the events so they go the first channel? Here are a few things that I can guide you with:
1. You can't get events that you triggered on the same channel.
2. Event triggering feature of the protocol is not for sending messages by its meaning, it's for very basic notifications (showing online status, typing whispers) because it's not guaranteed that it will be delivered to the channel. In order to actually send message with guaranteed result - you must send it with REST API.

Did it help?

**Comment by zamirszn** [comment] 2023-05-16 08:15
> @zamirszn Add corresponding logs from the package too.

ok im going to add this below the code

**Comment by kerimamansaryyev** [comment] 2023-05-16 08:25
@zamirszn  I've noticed that you neither dispose the client nor the stream subscriptions in the dispose method so the client is still alive, and more of them spawn each time a user enters the page, also it might be messing the logs too. I suggest that you review your code to fix logical errors and use the small guide I've left above. I am sure that the issue has nothing to do with the package.

**Comment by kerimamansaryyev** [comment] 2023-05-16 08:32
Also you reinitialize `static` variables with the `late static` instantiated in `initState`. It must be giving a runtime exceptions because you can not use lately initialized variables unless they are ready but in the code yo try to use them right in the next line (initState goes after those lines). I'd suggest that you use getters instead:
BAD:
```dart
 static String privateChannelName = "private-user.$chatUserId"
```
GOOD:
```dart
String get privateChannelName => 'private-user.${widget.chatUserId}';
```
It's just a one example, your code may contain more of logical errors so try to review it with a senior Flutter developer if any. Let me know if it fixed so I can close the issue

**Comment by kerimamansaryyev** [comment] 2023-05-16 08:37
> > @zamirszn  I've noticed that you neither dispose the client nor the stream subscriptions are canceled in the dispose method so the client is still alive, and more of them spawn each time a user enters the page, also it might be messing the logs too. I suggest that you review your code to fix logical errors and use the small guide I've left above. I am sure that the issue has nothing to do with the package.
> 
> okay thank you , i had no idea i have to cancel the stream subscriptions too, i was only disposing the channels , how do i do that please ??

```dart
// StreamSubscription
someStreamsubscription.cancel();
// PusherChannelsClient
// You don't have to unsubscribe from the channels if you dispose the client. It unsubscribes them automatically when disposing
client.dispose();
```

**Comment by zamirszn** [comment] 2023-05-16 08:38
> > > @zamirszn  I've noticed that you neither dispose the client nor the stream subscriptions are canceled in the dispose method so the client is still alive, and more of them spawn each time a user enters the page, also it might be messing the logs too. I suggest that you review your code to fix logical errors and use the small guide I've left above. I am sure that the issue has nothing to do with the package.
> > 
> > okay thank you , i had no idea i have to cancel the stream subscriptions too, i was only disposing the channels , how do i do that please ??
> 
> ```dart
> // StreamSubscription
> someStreamsubscription.cancel();
> // PusherChannelsClient
> // You don't have to unsubscribe from the channels if you dispose the client. It unsubscribes them automatically when disposing
> client.dispose();
> ```

I'll do as you suggested, thanks for the help

**Comment by zamirszn** [comment] 2023-05-17 11:16
Its working fine now  , I called `client.dispose()` on `dispose()` like you suggested, i had no idea i have to dispose the client  , thanks a lot for your help man , i appreciate

**Closed** 2023-05-17 11:16 UTC
